name: Add All Components

on:
  push:
    branches:
      - main
    paths:
      - /**
      - preview/**/*.rs
      - preview/**/Cargo.toml
      - primitives/**/*.rs
      - primitives/**/Cargo.toml
      - .github/**
      - Cargo.toml

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - /**
      - preview/**/*.rs
      - preview/**/Cargo.toml
      - primitives/**/*.rs
      - primitives/**/Cargo.toml
      - .github/**
      - Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: github.event.pull_request.draft == false
    name: Add All Components
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
          version: 1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu,wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-on-failure: "false"
      - uses: cargo-bins/cargo-binstall@main
      - name: Install CLI
        run: cargo binstall dioxus-cli -y --force --version 0.7.0-rc.3
      - name: Add components and check
        run: cd test-harness && dx components add --all --path .. --force && cargo check --all-features
