name: Clean Up Preview

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create empty directory and store it in a variable
      run: echo "empty_dir=$(mktemp -d)" >> $GITHUB_ENV
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: "${{ env.empty_dir }}" # The folder the action should deploy.
        target-folder: "pr-preview/pr-${{ github.event.pull_request.number }}/"
        clean: true
        single-commit: true
